export enum NotificationEventTypeEnum {
	TextMessage = 'TextMessage',
	AudioMessage = 'AudioMessage',
	VideoMessage = 'VideoMessage',
	StickerMessage = 'StickerMessage',
	DocumentMessage = 'DocumentMessage',
	LocationMessage = 'LocationMessage',
	ImageMessage = 'ImageMessage',
	ContactsMessage = 'ContactsMessage',
	OrderReceived = 'OrderReceived',
	ButtonInteraction = 'ButtonInteraction',
	ListInteraction = 'ListInteraction',
	CustomerNumberChanged = 'CustomerNumberChanged',
	CustomerIdentityChanged = 'CustomerIdentityChanged',
	UnknownEvent = 'UnknownEvent',
	MessageSent = 'MessageSent',
	MessageDelivered = 'MessageDelivered',
	MessageRead = 'MessageRead',
	Reaction = 'Reaction',
	AdInteraction = 'AdInteraction',
	ProductInquiry = 'ProductInquiry',
	MessageDeleted = 'MessageDeleted',
	MessageFailed = 'MessageFailed',
	MessageUndelivered = 'MessageUndelivered',
	ReplyMessage = 'ReplyMessage'
}

export enum NotificationMessageTypeEnum {
	Contact = 'contacts',
	Text = 'text',
	Audio = 'audio',
	Video = 'Video',
	Document = 'document',
	Order = 'order',
	Sticker = 'sticker',
	Image = 'image',
	System = 'system',
	Location = 'location',
	Unknown = 'unknown',
	Interactive = 'interactive',
	Reaction = 'reaction',
	Button = 'button'
}
